@baseUrl = http://localhost:3000

### Get all users
GET {{baseUrl}}/users

### Get user by ID
@userId = 1
GET {{baseUrl}}/users/{{userId}}

### Create a new user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Hadi Hijazi",
  "email": "hadi.hijazi@example.com"
}

### Update user by ID
@userId = 1
PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "Hadi Hijazi",
  "email": "hadi.hijazi@example.com"
}

### Delete user by ID
@userId = 1
DELETE {{baseUrl}}/users/{{userId}}


### Get products with query parameters
@category = electronics
@sort = price_asc
GET {{baseUrl}}/products?category={{category}}&sort={{sort}}